---
title: "Week 4 example notebook"
output: html_notebook
---

# ???

```{r}
library(ISLR)
names(Hitters)
dim(Hitters)

library(leaps)
regfit.fwd <- regsubsets(Salary~., data=Hitters, nvmax=19, method="forward")
summary(regfit.fwd)

regfit.bwd <- regsubsets(Salary~., data=Hitters, nvmax=19, method="backward")
summary(regfit.bwd)

coef(regfit.fwd,7)
coef(regfit.bwd,7)
```

-----------------------------------------------------
# ????

```{r}
require(bestglm)
require(glmnet)

data(manpower)
x <- as.matrix(manpower[, 1:4])
y <- log(manpower$Hours)
lambda <- exp(seq(-8.1, 1, 0.1))
fit2 <- glmnet(x, y, alpha=1, lambda=lambda)

set.seed(1) # For reproducibility
cv.fit2 <- cv.glmnet(x, y, alpha=1, nfolds=5, lambda=lambda)
plot(fit2,xvar="lambda",label=T)
```



```{r}
require(bestglm)
require(glmnet)
data(manpower)
x <- as.matrix(manpower[, 1:4])
y <- log(manpower$Hours)
lambda <- exp(seq(-8.1, 1, 0.1))
fit2 <- glmnet(x, y, alpha=1, lambda=lambda)

set.seed(1) # For reproducibility
cv.fit2 <- cv.glmnet(x, y, alpha=1, nfolds=5, lambda=lambda)
plot(cv.fit2)
bestlam <- cv.fit2$lambda.min
bestlam
```

--------------------------------------
# Hitters dataset ????

```{r}
library(ISLR)
Hitters <- na.omit(Hitters)
x <- model.matrix(Salary~., Hitters)[, -1]
y <- Hitters$Salary
```



```{r}
require(bestglm)
require(glmnet)
library(ISLR)
Hitters <- na.omit(Hitters)
x <- model.matrix(Salary~., Hitters)[, -1]
y <- Hitters$Salary
lambda <- exp(seq(-8.1, 1, 0.1))

set.seed(1)
train <- sample(1:nrow(x), nrow(x)/2)
test <- (-train)
y.test <- y[test]

set.seed(1)
cv.out <- cv.glmnet(x[train,], y[train], alpha=0)
bestlam <- cv.out$lambda.min
bestlam

## From R3.6.0 or later
## [1] 326.0828
## Before R 3.6.0
## [1] 211.7416

```



```{r}
require(bestglm)
require(glmnet)
library(ISLR)
Hitters <- na.omit(Hitters)
x <- model.matrix(Salary~., Hitters)[, -1]
y <- Hitters$Salary
lambda <- exp(seq(-8.1, 1, 0.1))

set.seed(1)
train <- sample(1:nrow(x), nrow(x)/2)
test <- (-train)
y.test <- y[test]

set.seed(1)
cv.out <- cv.glmnet(x[train,], y[train], alpha=0)
bestlam <- cv.out$lambda.min

ridge.mod <- glmnet(x[train,], y[train], alpha=0)
ridge.pred <- predict(ridge.mod, s=bestlam, newx=x[test,])
mean((ridge.pred-y.test)^2)
```



```{r}
require(bestglm)
require(glmnet)
library(ISLR)
Hitters <- na.omit(Hitters)
x <- model.matrix(Salary~., Hitters)[, -1]
y <- Hitters$Salary
lambda <- exp(seq(-8.1, 1, 0.1))

set.seed(1)
train <- sample(1:nrow(x), nrow(x)/2)
test <- (-train)
y.test <- y[test]

set.seed(1)
cv.out <- cv.glmnet(x[train,], y[train], alpha=0)
bestlam <- cv.out$lambda.min

out <- glmnet(x, y, alpha=0)
predict(out, type="coefficients",s=bestlam)[1:20,]
```



```{r}
require(bestglm)
require(glmnet)
library(ISLR)
Hitters <- na.omit(Hitters)
x <- model.matrix(Salary~., Hitters)[, -1]
y <- Hitters$Salary
lambda <- exp(seq(-8.1, 1, 0.1))

set.seed(1)
train <- sample(1:nrow(x), nrow(x)/2)
test <- (-train)
y.test <- y[test]

set.seed(1)
cv.out <- cv.glmnet(x[train,], y[train], alpha=1)
bestlam <- cv.out$lambda.min
bestlam

## [1] 9.286955
## [1] 16.78016  before R 3.6.0
```

```{r}
lasso.mod <- glmnet(x[train,], y[train], alpha=1)
lasso.pred <- predict(lasso.mod, s=bestlam, newx=x[test,])
mean((lasso.pred-y.test)^2)

## [1] 143668.8
## [1] 100838.2 before R 3.6.0
```



```{r}
require(bestglm)
require(glmnet)
library(ISLR)
Hitters <- na.omit(Hitters)
x <- model.matrix(Salary~., Hitters)[, -1]
y <- Hitters$Salary
lambda <- exp(seq(-8.1, 1, 0.1))

set.seed(1)
train <- sample(1:nrow(x), nrow(x)/2)
test <- (-train)
y.test <- y[test]

set.seed(1)
cv.out <- cv.glmnet(x[train,], y[train], alpha=1)
bestlam <- cv.out$lambda.min

out <- glmnet(x, y, alpha=1)
predict(out, type="coefficients",s=bestlam)[1:20,]
```

